spring.datasource.url=jdbc:postgresql://localhost:5432/telegramBotTasker
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
telegram.bot.token=8434115911:AAErGAVcShOQ6HlXdBTrCfJyrSJGclj2mGU
